### ISSUE TITLE
User types for members with reserved keywords

### ISSUE THREAD

**Issue by AODQ** [gianm/d-json#4]
Right now, there's no way to have `jsonDecode` alias JSON variables to members of a D struct if that variable is a reserved keyword. For example, it might be `version` in the JSON file, but since it's reserved, there's no way to label it in D. Thus under this case the variable should be switched to `_version` before applying it to a member.

**Comment by gianm** [comment]
Hi AODQ, I am no longer working on this repo, but would happily review and merge a pull request if you wrote one for this (and if it includes a test).

**Comment by gianm** [comment]
Fixed by #5.
